'use client';

import { useState, useCallback, useRef, useEffect } from 'react';
import { useRouter, useSearchParams, usePathname } from 'next/navigation';
import type { Route } from 'next';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Info,
  Flame,
} from 'lucide-react';
import { IgnitingFlame } from '@/components/ui/igniting-flame';
import Image from 'next/image';
import Link from 'next/link';
import {
  activateCompanion,
  createCompanion,
  createSession,
  generateBackstory,
  generateRandomIdentity,
  type GenerateBackstoryResult,
} from '@/lib/api';
import { streamAnchorImages, type AnchorImage } from '@/lib/api/imagegen';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/hooks/use-auth';
import { useOnboardingStore, type VoiceOption } from '@/stores/onboarding-store';
import { QuickStartCarousel } from './quick-start-carousel';
import { trackOnboardingStep, trackOnboardingComplete, trackCompanionCreated } from '@/lib/analytics/meta-pixel';

// All 12 archetypes from the personality schema
const ARCHETYPES = [
  { id: 'caregiver', name: 'The Caregiver', description: 'Nurturing, supportive, and empathetic', icon: '🤗', traits: ['Compassionate', 'Patient', 'Protective'] },
  { id: 'sage', name: 'The Sage', description: 'Wise, thoughtful, and philosophical', icon: '🦉', traits: ['Knowledgeable', 'Reflective', 'Objective'] },
  { id: 'explorer', name: 'The Explorer', description: 'Curious, adventurous, and open-minded', icon: '🧭', traits: ['Curious', 'Bold', 'Independent'] },
  { id: 'creator', name: 'The Creator', description: 'Imaginative, expressive, and artistic', icon: '🎨', traits: ['Creative', 'Visionary', 'Expressive'] },
  { id: 'hero', name: 'The Hero', description: 'Brave, determined, and protective', icon: '⚔️', traits: ['Courageous', 'Driven', 'Honorable'] },
  { id: 'jester', name: 'The Jester', description: 'Playful, humorous, and lighthearted', icon: '🎭', traits: ['Witty', 'Fun', 'Spontaneous'] },
  { id: 'lover', name: 'The Lover', description: 'Passionate, intimate, and devoted', icon: '💕', traits: ['Romantic', 'Devoted', 'Sensual'] },
  { id: 'magician', name: 'The Magician', description: 'Transformative, visionary, and inspiring', icon: '✨', traits: ['Inspiring', 'Mystical', 'Transformative'] },
  { id: 'ruler', name: 'The Ruler', description: 'Confident, authoritative, and organized', icon: '👑', traits: ['Decisive', 'Structured', 'Commanding'] },
  { id: 'everyperson', name: 'The Everyperson', description: 'Relatable, down-to-earth, and friendly', icon: '🤝', traits: ['Authentic', 'Approachable', 'Grounded'] },
  { id: 'innocent', name: 'The Innocent', description: 'Optimistic, pure, and hopeful', icon: '🌸', traits: ['Optimistic', 'Trusting', 'Joyful'] },
  { id: 'rebel', name: 'The Rebel', description: 'Unconventional, bold, and independent', icon: '🔥', traits: ['Defiant', 'Edgy', 'Authentic'] },
] as const;

type Archetype = typeof ARCHETYPES[number];

// Note: Appearance options are now generated by the LLM

// Quick-start schema - minimal validation
const quickStartSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters').max(30, 'Name must be 30 characters or less'),
});

type QuickStartFormValues = z.infer<typeof quickStartSchema>;

// Available voices for random selection
const availableVoices: VoiceOption[] = [
  { id: 'EXAVITQu4vr4xnSDxMaL', name: 'Sarah', description: 'Soft, warm', sampleUrl: '', gender: 'feminine' },
  { id: 'FGY2WhTYpPnrIDTdsKH5', name: 'Laura', description: 'Calm, soothing', sampleUrl: '', gender: 'feminine' },
  { id: 'XB0fDUnXU5powFXDhCwa', name: 'Charlotte', description: 'Elegant, confident', sampleUrl: '', gender: 'feminine' },
  { id: 'pFZP5JQG7iQjIQuC4Bku', name: 'Lily', description: 'Sweet, youthful', sampleUrl: '', gender: 'feminine' },
  { id: 'cgSgspJ2msm6clMCkdW9', name: 'Jessica', description: 'Expressive, friendly', sampleUrl: '', gender: 'feminine' },
  { id: 'onwK4e9ZLuTAKqWW03F9', name: 'Daniel', description: 'Deep, resonant', sampleUrl: '', gender: 'masculine' },
  { id: 'cjVigY5qzO86Huf0OWal', name: 'Eric', description: 'Smooth, charming', sampleUrl: '', gender: 'masculine' },
  { id: 'N2lVS1w4EtoT3dr4eOWO', name: 'Callum', description: 'Warm, intimate', sampleUrl: '', gender: 'masculine' },
  { id: 'JBFqnCBsd6RMkjVDRZzb', name: 'George', description: 'Rich, thoughtful', sampleUrl: '', gender: 'masculine' },
];

// Type for generated companion data
type SizeCategory = 'S' | 'M' | 'L' | 'XL';
type FemaleBodyType = 'slim' | 'athletic' | 'curvy' | 'plus-size';
type MaleBodyType = 'slim' | 'athletic' | 'muscular' | 'dad-bod';
type Ethnicity = 'east-asian' | 'south-asian' | 'black' | 'caucasian' | 'latina' | 'middle-eastern' | 'mixed';
type HairColor = 'black' | 'brown' | 'blonde' | 'red' | 'fantasy';

interface FemaleAppearance {
  gender: 'female';
  ethnicity: Ethnicity;
  bodyType: FemaleBodyType;
  hairColor: HairColor;
  breastSize: SizeCategory;
}

interface MaleAppearance {
  gender: 'male';
  ethnicity: Ethnicity;
  bodyType: MaleBodyType;
  hairColor: HairColor;
  build: SizeCategory;
}

type CompanionAppearance = FemaleAppearance | MaleAppearance;

interface GeneratedCompanionData {
  primaryArchetype: Archetype;
  secondaryArchetype: Archetype | null;
  pronouns: string;
  personality: {
    warmth: number;
    energy: number;
    playfulness: number;
    formality: number;
    assertiveness: number;
    curiosity: number;
    empathy: number;
    spontaneity: number;
    optimism: number;
    directness: number;
  };
  visualStyle: {
    appearance: CompanionAppearance;
  };
  voice: VoiceOption;
  boundaries: {
    relationship_pacing: string;
    content_rating: string;
    emotional_depth: 'surface' | 'moderate' | 'deep';
    topics_avoid: string[];
    safe_topics: string[];
  };
  backstoryContext?: {
    occupation?: string;
    distinctiveFeatures?: string[];
    dressStyle?: string;
    vibe?: string;
  };
}

interface QuickStartProps {
  onBack?: () => void; // Deprecated, kept for backwards compatibility
}

type RevealPhase = 'loading' | 'images' | 'ready';

const QUICK_START_PENDING_KEY = 'pendingQuickStart';
const QUICK_START_PENDING_TTL_MS = 15 * 60 * 1000;
const QUICK_START_PENDING_VERSION = 1;

interface PendingQuickStartPayload {
  version: number;
  createdAt: number;
  expiresAt: number;
  name: string;
  companion: GeneratedCompanionData;
}

function isPendingQuickStartPayload(value: unknown): value is PendingQuickStartPayload {
  if (!value || typeof value !== 'object') return false;

  const candidate = value as {
    version?: unknown;
    createdAt?: unknown;
    expiresAt?: unknown;
    name?: unknown;
    companion?: unknown;
  };

  return (
    typeof candidate.version === 'number' &&
    typeof candidate.createdAt === 'number' &&
    typeof candidate.expiresAt === 'number' &&
    candidate.version <= QUICK_START_PENDING_VERSION &&
    typeof candidate.name === 'string' &&
    Boolean(candidate.name.trim()) &&
    typeof candidate.companion === 'object' &&
    candidate.companion !== null
  );
}

function isPendingQuickStartFresh(payload: PendingQuickStartPayload, now = Date.now()): boolean {
  return payload.expiresAt > now && payload.createdAt <= now;
}

function getPendingQuickStartPayload(): PendingQuickStartPayload | null {
  const raw = sessionStorage.getItem(QUICK_START_PENDING_KEY);
  if (!raw) return null;

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }

  if (!isPendingQuickStartPayload(parsed)) return null;
  return parsed;
}

function buildPendingQuickStartPayload(name: string, companion: GeneratedCompanionData): PendingQuickStartPayload {
  const now = Date.now();
  return {
    version: QUICK_START_PENDING_VERSION,
    createdAt: now,
    expiresAt: now + QUICK_START_PENDING_TTL_MS,
    name,
    companion,
  };
}

// Generate random companion data locally (for unauthenticated users)
function generateLocalRandomCompanion(): GeneratedCompanionData {
  const randomArchetype = ARCHETYPES[Math.floor(Math.random() * ARCHETYPES.length)];
  const otherArchetypes = ARCHETYPES.filter(a => a.id !== randomArchetype.id);
  const secondaryArchetype = Math.random() > 0.5 ? otherArchetypes[Math.floor(Math.random() * otherArchetypes.length)] : null;

  const ethnicities: Ethnicity[] = ['east-asian', 'south-asian', 'black', 'caucasian', 'latina', 'middle-eastern', 'mixed'];
  const femaleBodyTypes: FemaleBodyType[] = ['slim', 'athletic', 'curvy', 'plus-size'];
  const maleBodyTypes: MaleBodyType[] = ['slim', 'athletic', 'muscular', 'dad-bod'];
  const hairColors: HairColor[] = ['black', 'brown', 'blonde', 'red', 'fantasy'];
  const sizeCategories: SizeCategory[] = ['S', 'M', 'L', 'XL'];

  const femVoices = availableVoices.filter(v => v.gender === 'feminine');
  const mascVoices = availableVoices.filter(v => v.gender === 'masculine');

  // Randomly pick gender
  const isMale = Math.random() > 0.5;
  const voicePool = isMale ? mascVoices : femVoices;

  // Generate gender-specific appearance
  const ethnicity = ethnicities[Math.floor(Math.random() * ethnicities.length)];
  const hairColor = hairColors[Math.floor(Math.random() * hairColors.length)];
  const size = sizeCategories[Math.floor(Math.random() * sizeCategories.length)];

  const appearance: CompanionAppearance = isMale
    ? {
        gender: 'male',
        ethnicity,
        bodyType: maleBodyTypes[Math.floor(Math.random() * maleBodyTypes.length)],
        hairColor,
        build: size,
      }
    : {
        gender: 'female',
        ethnicity,
        bodyType: femaleBodyTypes[Math.floor(Math.random() * femaleBodyTypes.length)],
        hairColor,
        breastSize: size,
      };

  // Set pronouns based on randomly selected gender
  const pronouns = isMale ? 'he/him' : 'she/her';

  return {
    primaryArchetype: randomArchetype,
    secondaryArchetype,
    pronouns,
    personality: {
      warmth: 0.4 + Math.random() * 0.4,
      energy: 0.3 + Math.random() * 0.5,
      playfulness: 0.3 + Math.random() * 0.5,
      formality: 0.2 + Math.random() * 0.4,
      assertiveness: 0.3 + Math.random() * 0.4,
      curiosity: 0.4 + Math.random() * 0.4,
      empathy: 0.5 + Math.random() * 0.4,
      spontaneity: 0.3 + Math.random() * 0.4,
      optimism: 0.4 + Math.random() * 0.4,
      directness: 0.3 + Math.random() * 0.4,
    },
    visualStyle: {
      appearance,
    },
    voice: voicePool[Math.floor(Math.random() * voicePool.length)],
    boundaries: {
      relationship_pacing: 'moderate',
      content_rating: 'R',
      emotional_depth: 'moderate' as const,
      topics_avoid: [] as string[],
      safe_topics: [] as string[],
    },
  };
}

export function QuickStart({ onBack }: QuickStartProps) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const pathname = usePathname();
  const { toast } = useToast();
  const { isAuthenticated, isInitialized } = useAuth();
  const { setQuickStartActive } = useOnboardingStore();

  // Transient local state for flame animation (not URL-persisted)
  const [isTransitioning, setIsTransitioning] = useState(false);

  // Derive step from URL - URL is the single source of truth
  const phaseParam = searchParams.get('phase');
  const step: 'name' | 'transition' | 'carousel' | 'creating' = isTransitioning
    ? 'transition'
    : phaseParam === 'carousel'
      ? 'carousel'
      : phaseParam === 'creating'
        ? 'creating'
        : 'name';

  // Track if carousel was ever completed (survives carousel remount on back navigation)
  const carouselCompletedRef = useRef(false);
  if (phaseParam === 'creating') {
    carouselCompletedRef.current = true;
  }

  // Helper to navigate to a phase
  const navigateToPhase = useCallback((phase: 'carousel' | 'creating' | null) => {
    const routeBase = pathname || '/onboard';
    const newParams = new URLSearchParams(searchParams.toString());
    if (phase) {
      newParams.set('phase', phase);
    } else {
      newParams.delete('phase');
      newParams.delete('qs');
    }
    const queryString = newParams.toString();
    const targetPath = (queryString ? `${routeBase}?${queryString}` : routeBase) as Route;
    router.push(targetPath, { scroll: false });
  }, [pathname, searchParams, router]);

  const [isCreating, setIsCreating] = useState(false);
  const [isNavigatingToChat, setIsNavigatingToChat] = useState(false);
  const navigateToChatTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [generatedCompanion, setGeneratedCompanion] = useState<GeneratedCompanionData | null>(null);

  // Sync quickStartActive with carousel step
  useEffect(() => {
    setQuickStartActive(step === 'carousel');
    return () => setQuickStartActive(false);
  }, [step, setQuickStartActive]);

  // Auto-advance from transition to carousel after flame animation
  useEffect(() => {
    if (isTransitioning && generatedCompanion) {
      const timer = setTimeout(() => {
        setIsTransitioning(false);
        navigateToPhase('carousel');
      }, 1200); // Duration of flame animation
      return () => clearTimeout(timer);
    }
  }, [isTransitioning, generatedCompanion, navigateToPhase]);
  const [apiPromise, setApiPromise] = useState<Promise<{ companionId: string; sessionId: string }> | null>(null);
  const nameInputRef = useRef<HTMLInputElement>(null);
  const streamCleanupRef = useRef<(() => void) | null>(null);

  // Review screen state
  const [revealPhase, setRevealPhase] = useState<RevealPhase>('loading');
  const [backstoryResult, setBackstoryResult] = useState<GenerateBackstoryResult | null>(null);
  const [anchorImages, setAnchorImages] = useState<AnchorImage[]>([]);
  const [visibleImageCount, setVisibleImageCount] = useState(0);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [anchorsGenerationComplete, setAnchorsGenerationComplete] = useState(false);

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors, isValid },
  } = useForm<QuickStartFormValues>({
    resolver: zodResolver(quickStartSchema),
    mode: 'onChange',
    defaultValues: {
      name: '',
    },
  });

  const companionName = watch('name');
  const hasRestoredPendingRef = useRef(false);

  // Focus name input on mount
  useEffect(() => {
    if (step === 'name') {
      nameInputRef.current?.focus();
    }
  }, [step]);

  useEffect(() => {
    return () => {
      if (streamCleanupRef.current) {
        streamCleanupRef.current();
        streamCleanupRef.current = null;
      }
      if (navigateToChatTimeoutRef.current) {
        clearTimeout(navigateToChatTimeoutRef.current);
        navigateToChatTimeoutRef.current = null;
      }
    };
  }, []);

  // Start API calls in background while carousel plays
  const startApiCalls = useCallback(async (name: string, randomCompanion: GeneratedCompanionData) => {
    setAnchorsGenerationComplete(false);

    const personalityDescription = [
      randomCompanion.primaryArchetype.description,
      randomCompanion.secondaryArchetype
        ? `Secondary archetype: ${randomCompanion.secondaryArchetype.name}`
        : '',
      `Traits: ${randomCompanion.primaryArchetype.traits.join(', ')}`,
      `Warmth: ${Math.round(randomCompanion.personality.warmth * 100)}%`,
      `Playfulness: ${Math.round(randomCompanion.personality.playfulness * 100)}%`,
      `Empathy: ${Math.round(randomCompanion.personality.empathy * 100)}%`,
      `Energy: ${Math.round(randomCompanion.personality.energy * 100)}%`,
    ].filter(Boolean).join('\n');

    // Create the companion with random values
    const companion = await createCompanion({
      name,
      description: randomCompanion.primaryArchetype.description,
      personality: personalityDescription,
      voiceId: randomCompanion.voice.id,
      isPublic: false,
      spec: {
        identity: {
          name,
          pronouns: randomCompanion.pronouns,
        },
        personality: {
          archetype: randomCompanion.primaryArchetype.id,
          secondary_archetype: randomCompanion.secondaryArchetype?.id,
          traits: randomCompanion.personality,
        },
        voice: {
          provider: 'elevenlabs',
          voice_id: randomCompanion.voice.id,
        },
        visual_style: randomCompanion.visualStyle,
        boundaries: randomCompanion.boundaries,
      },
    });

    // Start streaming anchor images - wait for at least one before proceeding
    // Note: personality values are stored as 0-1 floats, but image gen expects 0-100 integers
    console.log('[QuickStart] Starting anchor image generation for companion:', companion.id);

    // Create a promise that resolves when first anchor is received
    const firstAnchorPromise = new Promise<void>((resolve, reject) => {
      let resolved = false;

      if (streamCleanupRef.current) {
        streamCleanupRef.current();
        streamCleanupRef.current = null;
      }

      streamCleanupRef.current = streamAnchorImages(
        {
          companionId: companion.id,
          appearance: randomCompanion.visualStyle.appearance,
          personality: {
            warmth: Math.round(randomCompanion.personality.warmth * 100),
            playfulness: Math.round(randomCompanion.personality.playfulness * 100),
            directness: Math.round(randomCompanion.personality.directness * 100),
            curiosity: Math.round(randomCompanion.personality.curiosity * 100),
            empathy: Math.round(randomCompanion.personality.empathy * 100),
            assertiveness: Math.round(randomCompanion.personality.assertiveness * 100),
          },
          backstoryContext: randomCompanion.backstoryContext,
        },
        {
          onProgress: (data) => {
            console.log('[QuickStart] Anchor progress:', data);
          },
          onAnchor: (anchor) => {
            console.log('[QuickStart] Anchor received:', anchor);
            // Add anchor to state as they come in
            setAnchorImages((prev) => [...prev, anchor]);
            // Resolve when first anchor is received
            if (!resolved) {
              resolved = true;
              resolve();
            }
          },
          onComplete: (result) => {
            console.log('[QuickStart] Anchor generation complete:', result);
            streamCleanupRef.current = null;
            setAnchorsGenerationComplete(true);
            // Also resolve on complete in case no anchors were received
            if (!resolved) {
              resolved = true;
              resolve();
            }
          },
          onError: (error) => {
            console.error('[QuickStart] Anchor generation error:', error);
            streamCleanupRef.current = null;
            setAnchorsGenerationComplete(true);
            // Resolve even on error so we don't block forever
            if (!resolved) {
              resolved = true;
              resolve();
            }
          },
        }
      );
    });

    // Fire off backstory generation - track result in state
    // Note: personality values are stored as 0-1 floats, but orchestrator expects 0-100 integers
    generateBackstory(companion.id, {
      archetype: randomCompanion.primaryArchetype.id,
      secondaryArchetype: randomCompanion.secondaryArchetype?.id,
      archetypeDescription: randomCompanion.primaryArchetype.description,
      personality: {
        warmth: Math.round(randomCompanion.personality.warmth * 100),
        energy: Math.round(randomCompanion.personality.energy * 100),
        playfulness: Math.round(randomCompanion.personality.playfulness * 100),
        formality: Math.round(randomCompanion.personality.formality * 100),
        assertiveness: Math.round(randomCompanion.personality.assertiveness * 100),
        curiosity: Math.round(randomCompanion.personality.curiosity * 100),
        empathy: Math.round(randomCompanion.personality.empathy * 100),
        spontaneity: Math.round(randomCompanion.personality.spontaneity * 100),
        optimism: Math.round(randomCompanion.personality.optimism * 100),
        directness: Math.round(randomCompanion.personality.directness * 100),
      },
      tenets: [],
    })
      .then((result) => {
        console.log('[QuickStart] Backstory generated:', result);
        setBackstoryResult(result);
      })
      .catch((err) => {
        console.error('Backstory generation failed:', err);
        // Provide fallback so we can still progress
        setBackstoryResult({ backstory: '', motivations: [], keyMemories: [], personalityQuirks: [], latencyMs: 0 });
      });

    // Wait for at least one anchor image before proceeding
    console.log('[QuickStart] Waiting for first anchor image...');
    await firstAnchorPromise;
    console.log('[QuickStart] First anchor received, creating session...');

    console.log('[QuickStart] Activating companion before session creation...');
    await activateCompanion(companion.id);

    // Create a session
    const session = await createSession({
      companionId: companion.id,
      title: `Chat with ${name}`,
    });

    // Store session ID in state
    setSessionId(session.id);

    // Track companion creation
    trackCompanionCreated(companion.id);

    return { companionId: companion.id, sessionId: session.id };
  }, []);

  // Restore pending quick-start data after signup and continue creation.
  useEffect(() => {
    if (hasRestoredPendingRef.current || !isAuthenticated) return;

    const payload = getPendingQuickStartPayload();
    if (!payload) {
      sessionStorage.removeItem(QUICK_START_PENDING_KEY);
      hasRestoredPendingRef.current = true;
      return;
    }

    if (!isPendingQuickStartFresh(payload)) {
      sessionStorage.removeItem(QUICK_START_PENDING_KEY);
      hasRestoredPendingRef.current = true;
      return;
    }

    hasRestoredPendingRef.current = true;
    sessionStorage.removeItem(QUICK_START_PENDING_KEY);

    try {
      const parsed = payload;
      if (!parsed.name || !parsed.companion) return;

      setValue('name', parsed.name, { shouldValidate: true });
      setGeneratedCompanion(parsed.companion);
      navigateToPhase('creating');
      setRevealPhase('loading');
      setBackstoryResult(null);
      setAnchorImages([]);
      setVisibleImageCount(0);
      setSessionId(null);
      setAnchorsGenerationComplete(false);
      setIsCreating(true);

      const promise = startApiCalls(parsed.name, parsed.companion);
      setApiPromise(promise);
      promise
        .then(() => setIsCreating(false))
        .catch((error) => {
          console.error('Restored quick start creation failed:', error);
          toast({
            title: 'Creation failed',
            description: 'Something went wrong. Please try again.',
            variant: 'destructive',
          });
          setIsCreating(false);
          setAnchorsGenerationComplete(false);
          navigateToPhase(null);
          setApiPromise(null);
        });
    } catch {
      // Ignore malformed session payloads.
    }
  }, [isAuthenticated, navigateToPhase, setValue, startApiCalls, toast]);

  // Handle name submission - generate companion data and optionally start API calls
  const onNameSubmit = useCallback(async () => {
    if (!isValid || !companionName) return;

    setRevealPhase('loading');
    setBackstoryResult(null);
    setAnchorImages([]);
    setVisibleImageCount(0);
    setSessionId(null);
    setAnchorsGenerationComplete(false);
    setApiPromise(null);

    // Track quick start name step
    trackOnboardingStep(1, 'quick-name', 'quick');

    // Immediately show the flame transition
    setIsTransitioning(true);

    try {
      let randomCompanion: GeneratedCompanionData;

      if (isAuthenticated) {
        // Authenticated: Generate full companion via LLM (pass name for gender inference)
        const llmGenerated = await generateRandomIdentity(companionName);

        // Find archetype objects from LLM-generated IDs
        const primaryArchetype = ARCHETYPES.find(a => a.id === llmGenerated.archetype) || ARCHETYPES[0];
        const secondaryArchetype = llmGenerated.secondaryArchetype
          ? ARCHETYPES.find(a => a.id === llmGenerated.secondaryArchetype) || null
          : null;

        // Select voice based on LLM-generated gender preference
        const voicesByGender = availableVoices.filter(v => v.gender === llmGenerated.voiceGender);
        const selectedVoice = voicesByGender.length > 0
          ? voicesByGender[Math.floor(Math.random() * voicesByGender.length)]
          : availableVoices[0];

        // Build companion data from LLM response (gender-aware)
        const llmAppearance: CompanionAppearance = llmGenerated.appearance.gender === 'male'
          ? {
              gender: 'male',
              ethnicity: llmGenerated.appearance.ethnicity as Ethnicity,
              bodyType: llmGenerated.appearance.bodyType as MaleBodyType,
              hairColor: llmGenerated.appearance.hairColor as HairColor,
              build: (llmGenerated.appearance.build || 'M') as SizeCategory,
            }
          : {
              gender: 'female',
              ethnicity: llmGenerated.appearance.ethnicity as Ethnicity,
              bodyType: llmGenerated.appearance.bodyType as FemaleBodyType,
              hairColor: llmGenerated.appearance.hairColor as HairColor,
              breastSize: (llmGenerated.appearance.breastSize || 'M') as SizeCategory,
            };

        randomCompanion = {
          primaryArchetype,
          secondaryArchetype,
          pronouns: llmGenerated.pronouns,
          personality: {
            warmth: llmGenerated.personality.warmth / 100,
            energy: llmGenerated.personality.energy / 100,
            playfulness: llmGenerated.personality.playfulness / 100,
            formality: llmGenerated.personality.formality / 100,
            assertiveness: llmGenerated.personality.assertiveness / 100,
            curiosity: llmGenerated.personality.curiosity / 100,
            empathy: llmGenerated.personality.empathy / 100,
            spontaneity: llmGenerated.personality.spontaneity / 100,
            optimism: llmGenerated.personality.optimism / 100,
            directness: llmGenerated.personality.directness / 100,
          },
          visualStyle: {
            appearance: llmAppearance,
          },
          voice: selectedVoice,
          boundaries: {
            relationship_pacing: 'moderate',
            content_rating: 'R',
            emotional_depth: 'moderate' as const,
            topics_avoid: [] as string[],
            safe_topics: [] as string[],
          },
          backstoryContext: {
            occupation: llmGenerated.occupation || undefined,
            distinctiveFeatures: llmGenerated.distinctiveFeatures.length > 0 ? llmGenerated.distinctiveFeatures : undefined,
            dressStyle: llmGenerated.dressStyle || undefined,
            vibe: llmGenerated.vibe || undefined,
          },
        };

        // Start API calls in background for authenticated users
        const promise = startApiCalls(companionName, randomCompanion);
        setApiPromise(promise);
      } else {
        // Unauthenticated: Generate companion data locally (no API calls)
        randomCompanion = generateLocalRandomCompanion();
        // No API calls - we'll create the companion after they sign up
      }

      // Set companion data - the auto-advance useEffect will transition to carousel
      setGeneratedCompanion(randomCompanion);
    } catch (error) {
      console.error('Failed to generate companion:', error);
      toast({
        title: 'Generation failed',
        description: 'Something went wrong. Please try again.',
        variant: 'destructive',
      });
      // Go back to name step on error
      setIsTransitioning(false);
      navigateToPhase(null);
    }
  }, [isValid, companionName, isAuthenticated, startApiCalls, toast, navigateToPhase]);

  // Handle carousel completion - wait for API and show review screen
  const onCarouselComplete = useCallback(async () => {
    if (!generatedCompanion) return;

    navigateToPhase('creating');
    setRevealPhase('loading');

    if (isAuthenticated && apiPromise) {
      // Authenticated: Wait for API calls to complete
      setIsCreating(true);
      // Phase transitions happen via useEffect based on anchor generation progress.
      try {
        await apiPromise;
        setIsCreating(false);
      } catch (error) {
        console.error('Quick start creation failed:', error);
        toast({
          title: 'Creation failed',
          description: 'Something went wrong. Please try again.',
          variant: 'destructive',
        });
        setIsCreating(false);
        setAnchorsGenerationComplete(false);
        navigateToPhase(null);
        setApiPromise(null);
      }
    } else {
      // Unauthenticated: Show simplified review immediately (no images/backstory)
      setIsCreating(false);
      // Provide fallback backstory so phase transitions work
      setBackstoryResult({
        backstory: `A ${generatedCompanion.primaryArchetype.description.toLowerCase()} companion ready to connect with you.`,
        motivations: [],
        keyMemories: [],
        personalityQuirks: [],
        latencyMs: 0,
      });
      // Skip directly to ready phase (no images to show)
      setRevealPhase('ready');
    }
  }, [apiPromise, generatedCompanion, isAuthenticated, toast, navigateToPhase]);

  // Phase transitions - loading → images → ready
  useEffect(() => {
    if (step !== 'creating') return;
    if (revealPhase !== 'loading') return;
    if (anchorImages.length > 0) {
      setRevealPhase('images');
      return;
    }
    if (anchorsGenerationComplete) {
      setRevealPhase('ready');
    }
  }, [anchorImages.length, anchorsGenerationComplete, revealPhase, step]);

  // Ensure first image appears when image phase starts.
  useEffect(() => {
    if (step !== 'creating') return;
    if (revealPhase === 'images' && anchorImages.length > 0 && visibleImageCount === 0) {
      setVisibleImageCount(1);
    }
  }, [revealPhase, anchorImages.length, visibleImageCount, step]);

  // Stagger image reveals
  useEffect(() => {
    if (step !== 'creating') return;
    if (revealPhase === 'images' && visibleImageCount < anchorImages.length) {
      const timer = setTimeout(() => {
        setVisibleImageCount((prev) => prev + 1);
      }, 600); // 600ms between each image
      return () => clearTimeout(timer);
    }
  }, [revealPhase, visibleImageCount, anchorImages.length, step]);

  // Transition to ready after all images shown
  useEffect(() => {
    if (step !== 'creating') return;
    if (
      revealPhase === 'images' &&
      anchorsGenerationComplete &&
      visibleImageCount >= anchorImages.length &&
      anchorImages.length > 0
    ) {
      const timer = setTimeout(() => {
        setRevealPhase('ready');
      }, 800);
      return () => clearTimeout(timer);
    }
  }, [revealPhase, visibleImageCount, anchorImages.length, anchorsGenerationComplete, step]);

  // Handle ignite - redirect to chat or signup
  const handleIgnite = useCallback(() => {
    if (!isAuthenticated && !isInitialized) {
      return;
    }

    if (isNavigatingToChat) return;
    // Track onboarding completion
    trackOnboardingComplete('quick', 4);

    if (!isAuthenticated) {
      // Store companion data for after signup and redirect to signup
      if (generatedCompanion && companionName) {
        const payload = buildPendingQuickStartPayload(companionName, generatedCompanion);
        sessionStorage.setItem(QUICK_START_PENDING_KEY, JSON.stringify(payload));
      }
      const returnTo = pathname || '/onboard';
      router.push(`/signup?returnTo=${encodeURIComponent(returnTo)}`);
      return;
    }

    if (!sessionId) return;
    if (typeof window !== 'undefined') {
      window.sessionStorage.setItem('campfire:onboard-completion-session', sessionId);
    }
    setIsNavigatingToChat(true);
    if (navigateToChatTimeoutRef.current) {
      clearTimeout(navigateToChatTimeoutRef.current);
    }
    navigateToChatTimeoutRef.current = setTimeout(() => {
      setIsNavigatingToChat(false);
    }, 1200);
    router.push(`/chat/${sessionId}`);
  }, [isInitialized, isAuthenticated, isNavigatingToChat, sessionId, router, generatedCompanion, companionName, pathname]);

  return (
    <div className={`w-full mx-auto ${step === 'carousel' ? 'max-w-5xl' : 'max-w-2xl'}`}>
      <AnimatePresence mode="wait">
        {/* Step 1: Name */}
        {step === 'name' && (
          <motion.div
            key="name-step"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, filter: 'blur(10px)' }}
            transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
            className="space-y-8"
          >
            <form onSubmit={handleSubmit(onNameSubmit)} className="space-y-6">
              <div className="space-y-6 text-center">
                <h2 className="text-3xl md:text-4xl font-bold font-display tracking-tight text-white">
                  What should we call your companion?
                </h2>
                <Input
                  {...register('name')}
                  ref={(e) => {
                    register('name').ref(e);
                    (nameInputRef as React.MutableRefObject<HTMLInputElement | null>).current = e;
                  }}
                  placeholder="Enter a name..."
                  className="bg-white/[0.03] border-white/10 h-16 lg:h-20 text-xl lg:text-3xl focus:ring-vibes-cyan focus:border-vibes-cyan font-sans transition-all text-center"
                  autoComplete="off"
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && isValid) {
                      e.preventDefault();
                      onNameSubmit();
                    }
                  }}
                />
                {errors.name && (
                  <p className="text-sm text-vibes-hot font-medium text-center">{errors.name.message}</p>
                )}
              </div>

              <div className="flex pt-4">
                <Button
                  type="submit"
                  size="lg"
                  disabled={!isValid}
                  className="flex-1 h-16 md:h-20 rounded-2xl bg-gradient-to-r from-vibes-cyan to-vibes-neon hover:shadow-[0_0_30px_rgba(6,182,212,0.3)] transition-all font-bold text-xl md:text-2xl disabled:opacity-50"
                >
                  Create Companion
                </Button>
              </div>
            </form>
          </motion.div>
        )}

        {/* Transition: Flame ignition animation */}
        {step === 'transition' && (
          <motion.div
            key="transition-step"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0, scale: 1.2 }}
            transition={{ duration: 0.3 }}
            className="flex items-center justify-center min-h-[60vh] md:min-h-[300px]"
          >
            <IgnitingFlame size={120} />
          </motion.div>
        )}

        {/* Step 2: Carousel */}
        {step === 'carousel' && generatedCompanion && (
          <motion.div
            key="carousel-step"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.98 }}
            transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
            className="w-full"
          >
            <QuickStartCarousel
              companionName={companionName}
              generatedData={generatedCompanion}
              onComplete={onCarouselComplete}
              autoAdvance={!carouselCompletedRef.current}
            />
          </motion.div>
        )}

        {/* Step 3: Review Screen (same as manual flow) */}
        {step === 'creating' && (
          <motion.div
            key="creating-step"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5 }}
            className="min-h-[60vh] flex flex-col items-center pt-16 md:pt-16"
          >
            <AnimatePresence mode="wait">
              {/* Phase 1: Loading - Flame */}
              {revealPhase === 'loading' && (
                <motion.div
                  key="loading"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0, scale: 1.5 }}
                  transition={{ duration: 0.5 }}
                  className="flex items-center justify-center"
                >
                  <motion.div
                    animate={{ scale: [1, 1.1, 1] }}
                    transition={{
                      duration: 2,
                      repeat: Infinity,
                      ease: 'easeInOut',
                    }}
                    className="relative"
                  >
                    {/* Glow effect */}
                    <motion.div
                      className="absolute inset-0 blur-3xl"
                      animate={{ opacity: [0.4, 0.7, 0.4], scale: [1.3, 1.6, 1.3] }}
                      transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                      style={{
                        background: 'radial-gradient(circle, rgba(249,115,22,0.6) 0%, rgba(239,68,68,0.3) 50%, transparent 70%)',
                      }}
                    />
                    <Flame className="h-24 w-24 text-orange-500 relative z-10" />
                  </motion.div>
                </motion.div>
              )}

              {/* Phase 2 & 3: Image Reveal & Backstory Overlay */}
              {(revealPhase === 'images' || revealPhase === 'ready') && generatedCompanion && (
                <motion.div
                  key="images"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.5 }}
                  className="text-center w-full max-w-xl mx-auto px-4"
                >
                  {/* Hero image */}
                  {anchorImages[0] && visibleImageCount >= 1 && (
                    <motion.div
                      initial={{ scale: 0, rotate: -8, opacity: 0 }}
                      animate={{ scale: 1, rotate: 0, opacity: 1 }}
                      transition={{ type: 'spring', stiffness: 150, damping: 15 }}
                      className="relative aspect-[3/4] w-full max-w-sm mx-auto rounded-2xl overflow-hidden"
                    >
                      {/* Glow burst */}
                      <motion.div
                        initial={{ scale: 0.5, opacity: 0.9 }}
                        animate={{ scale: 2, opacity: 0 }}
                        transition={{ duration: 0.8 }}
                        className="absolute inset-0 bg-vibes-neon/50 rounded-2xl blur-3xl -z-10"
                      />
                      {/* Border glow */}
                      <div className="absolute inset-0 rounded-2xl border-2 border-vibes-neon/60 shadow-[0_0_60px_rgba(168,85,247,0.6)] z-10" />
                      <Image
                        src={anchorImages[0].url}
                        alt={companionName}
                        fill
                        className="object-cover"
                        priority
                      />
                      {/* Identity & backstory overlay */}
                      <div className="absolute bottom-0 left-0 right-0 p-5 bg-gradient-to-t from-black/95 via-black/80 to-transparent z-20">
                        <h2 className="text-3xl font-bold font-display text-white mb-1">{companionName}</h2>
                        <p className="text-gray-300 text-xs uppercase tracking-wider">
                          {generatedCompanion.pronouns} • {generatedCompanion.primaryArchetype.name}
                          {generatedCompanion.secondaryArchetype && (
                            <>
                              {' + '}
                              <span className="text-vibes-cyan">{generatedCompanion.secondaryArchetype.name}</span>
                            </>
                          )}
                        </p>
                        <AnimatePresence>
                          {backstoryResult && (
                            <motion.p
                              key="backstory-overlay"
                              initial={{ opacity: 0, y: 16, filter: 'blur(6px)' }}
                              animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
                              exit={{ opacity: 0, y: 16 }}
                              transition={{ delay: 0.2, duration: 0.45 }}
                              className="mt-2 text-sm leading-relaxed text-gray-100 font-light line-clamp-3"
                            >
                              {backstoryResult.backstory || `A ${generatedCompanion.primaryArchetype.description.toLowerCase()} companion waiting to connect.`}
                            </motion.p>
                          )}
                        </AnimatePresence>
                      </div>
                    </motion.div>
                  )}

                  {/* Thumbnails */}
                  {anchorImages.length > 1 && (
                    <div className="flex gap-3 justify-center mt-6">
                      {anchorImages.slice(1).map((anchor, index) => (
                        visibleImageCount >= index + 2 && (
                          <motion.div
                            key={anchor.url}
                            initial={{ scale: 0, y: 30, opacity: 0 }}
                            animate={{ scale: 1, y: 0, opacity: 1 }}
                            transition={{
                              type: 'spring',
                              stiffness: 200,
                              damping: 15,
                            }}
                            className="relative w-20 h-28 rounded-xl overflow-hidden border-2 border-white/20 shadow-[0_0_20px_rgba(168,85,247,0.3)]"
                          >
                            {/* Thumbnail glow burst */}
                            <motion.div
                              initial={{ scale: 0.5, opacity: 0.7 }}
                              animate={{ scale: 1.5, opacity: 0 }}
                              transition={{ duration: 0.5 }}
                              className="absolute inset-0 bg-vibes-cyan/40 blur-xl -z-10"
                            />
                            <Image
                              src={anchor.url}
                              alt={`${companionName} variant`}
                              fill
                              className="object-cover"
                            />
                          </motion.div>
                        )
                      ))}
                    </div>
                  )}

                  {/* IGNITE Button */}
                  <AnimatePresence>
                    {(revealPhase === 'ready' || visibleImageCount >= 1) && backstoryResult && (sessionId || !isAuthenticated) && (
                      <motion.div
                        initial={{ y: 50, opacity: 0, scale: 0.9 }}
                        animate={{ y: 0, opacity: 1, scale: 1 }}
                        transition={{ type: 'spring', stiffness: 150, damping: 15, delay: 0.3 }}
                        className="mt-10"
                      >
                        <Button
                          size="lg"
                          onClick={handleIgnite}
                          className="h-auto py-6 px-16 text-2xl font-bold rounded-2xl bg-gradient-to-r from-orange-500 via-red-500 to-pink-500 hover:from-orange-400 hover:via-red-400 hover:to-pink-400 shadow-[0_0_40px_rgba(239,68,68,0.5)] hover:shadow-[0_0_60px_rgba(239,68,68,0.7)] transition-all duration-300 hover:scale-105 active:scale-95 flex-col gap-2 [&_svg]:h-[50px] [&_svg]:w-[50px]"
                        >
                          <Flame className="text-white" />
                          IGNITE
                        </Button>
                        <p className="text-xs text-center text-gray-500 mt-6">
                          By igniting {companionName}, you agree to our{' '}
                          <a href="/terms" className="underline hover:text-gray-300 transition-colors">Terms</a> and{' '}
                          <a href="/privacy" className="underline hover:text-gray-300 transition-colors">Privacy Policy</a>.
                        </p>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Tip at bottom */}
      {step === 'name' && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          className="mt-12 flex items-center justify-center gap-2 text-xs text-gray-500"
        >
          <Info className="h-3.5 w-3.5" />
          <span>You can customize your companion anytime from the dashboard</span>
        </motion.div>
      )}
    </div>
  );
}
