import { SectionHeader } from '@/components/layout/section-header';

export default function TermsPage() {
  return (
    <div className="container py-24 md:py-32 max-w-4xl mx-auto">
      <SectionHeader
        title="Terms of Service"
        description="Last updated: January 1, 2026"
        className="mb-12"
        align="left"
      />

      <div className="prose prose-slate dark:prose-invert max-w-none">
        <p>
          Please read these Terms of Service (&quot;Terms&quot;) carefully before using Campfire (&quot;Service&quot;). By accessing or using the Service, you agree to be bound by these Terms.
        </p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using our services, you agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, you may not use our services. You must be at least 18 years old to use this Service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          Campfire provides AI-powered companion services for entertainment and personal use. The AI companions are computer-generated and do not represent real persons. All interactions are simulated and generated by artificial intelligence systems.
        </p>

        <h2>3. User Accounts</h2>
        <p>
          You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password. You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.
        </p>

        <h2>4. User Content and Conduct</h2>
        <p>
          You are solely responsible for all content you submit to the Service. You agree not to use the Service to:
        </p>
        <ul>
          <li>Violate any applicable laws or regulations</li>
          <li>Infringe upon the rights of others</li>
          <li>Generate content depicting real persons without their consent</li>
          <li>Create content involving minors in any context</li>
          <li>Engage in harassment, abuse, or harmful behavior</li>
          <li>Attempt to circumvent safety systems or content filters</li>
          <li>Use the Service for any illegal purpose</li>
        </ul>

        <h2>5. AI-Generated Content Disclaimer</h2>
        <p>
          <strong>THE AI COMPANIONS ARE NOT REAL PERSONS.</strong> All responses, personalities, and content generated by AI companions are artificially created and should not be relied upon for:
        </p>
        <ul>
          <li>Medical, legal, financial, or professional advice</li>
          <li>Emergency services or crisis intervention</li>
          <li>Factual information or research</li>
          <li>Mental health treatment or therapy</li>
          <li>Any decisions with real-world consequences</li>
        </ul>
        <p>
          AI responses may be inaccurate, inappropriate, or harmful. You acknowledge that you use the Service at your own risk and that AI-generated content does not reflect the views of Campfire.
        </p>

        <h2>6. Intellectual Property</h2>
        <p>
          The Service and its original content, features, and functionality are owned by Campfire and are protected by international copyright, trademark, and other intellectual property laws. You retain ownership of content you create, but grant us a license to use, store, and process that content to provide the Service.
        </p>

        <h2>7. Payment and Subscriptions</h2>
        <p>
          Paid subscriptions are billed in advance on a recurring basis. You authorize us to charge your payment method automatically. Refunds are provided at our sole discretion. We reserve the right to change pricing at any time with notice.
        </p>

        <h2>8. Termination</h2>
        <p>
          We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will cease immediately. All provisions of the Terms which by their nature should survive termination shall survive.
        </p>

        <h2>9. Disclaimer of Warranties</h2>
        <p>
          <strong>THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.</strong> We do not warrant that the Service will be uninterrupted, secure, or error-free. We make no warranties regarding the accuracy, reliability, or quality of any content generated by AI companions.
        </p>

        <h2>10. Limitation of Liability</h2>
        <p>
          <strong>TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL CAMPFIRE, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:</strong>
        </p>
        <ul>
          <li>Your use or inability to use the Service</li>
          <li>Any content generated by AI companions</li>
          <li>Unauthorized access to or alteration of your data</li>
          <li>Any third-party conduct on the Service</li>
          <li>Any other matter relating to the Service</li>
        </ul>
        <p>
          <strong>OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR ONE HUNDRED DOLLARS ($100), WHICHEVER IS GREATER.</strong>
        </p>

        <h2>11. Indemnification</h2>
        <p>
          You agree to defend, indemnify, and hold harmless Campfire and its officers, directors, employees, and agents from any claims, damages, obligations, losses, liabilities, costs, or expenses arising from: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any third-party rights; or (d) any content you submit to the Service.
        </p>

        <h2>12. Dispute Resolution and Arbitration</h2>
        <p>
          Any disputes arising from these Terms or the Service shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association. You waive your right to participate in class action lawsuits or class-wide arbitration. This arbitration agreement shall survive termination of these Terms.
        </p>

        <h2>13. Governing Law</h2>
        <p>
          These Terms shall be governed by the laws of the State of Delaware, United States, without regard to its conflict of law provisions. Any legal action must be brought in the courts located in Delaware.
        </p>

        <h2>14. Severability</h2>
        <p>
          If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.
        </p>

        <h2>15. Entire Agreement</h2>
        <p>
          These Terms constitute the entire agreement between you and Campfire regarding the Service and supersede all prior agreements and understandings.
        </p>

        <h2>16. Changes to Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. We will notify you of material changes by posting the new Terms on this page and updating the &quot;Last updated&quot; date. Your continued use of the Service after changes constitutes acceptance of the new Terms.
        </p>

        <h2>17. Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us at legal@campfire.dev.
        </p>
      </div>
    </div>
  );
}
